### ISSUE TITLE
reagarding likelihood in "Bayesian model II regression in JAGS"

### ISSUE THREAD

**Issue by JeromeMathieuEcology** [mbjoseph/mbjoseph.github.io#3]
Hi,
First, thanks for sharing all this knowledge.
Regarding the "Bayesian model II regression in JAGS" post, in the likelihood of the model with error on x, I don't understand why it is truex that is used, I would have used obsx instead.
Thanks

**Comment by mbjoseph** [comment]
Hey @JeromeMathieuEcology! Can you clarify where you would have used `obsx` instead of `truex`? Here's the likelihood: 

```r
  for (i in 1:n){
    truex[i] ~ dnorm(0, .04)
    x[i] ~ dnorm(truex[i], taux)
    y[i] ~ dnorm(mu[i], tauy)
    mu[i] <- alpha + beta * truex[i]
  }
```

The assumption here is that `x[i]` is observed with error, and the `truex[i]` is the actual value of the covariate. Thus, the use of `truex[i]` in the equation for `mu[i]`.

There's some more info and a Stan example here: https://mc-stan.org/docs/2_18/stan-users-guide/bayesian-measurement-error-model.html
